ktor:
    application:
        modules:
            - com.example.ApplicationKt.module
    deployment:
        port: 8080
jwt:
  domain: "https://0.0.0.0:8080/"
  audience: "jwt-audience"
  realm: "ktor sample app"
